version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        NUXT_PORT: "${NUXT_PORT}"
        NUXT_HOST: "${HOST}"
    volumes:
      - ${APPLICATION_PATH}:/var/www
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    tty: true
    restart: always
